global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'rpi-monitor'
    node: 100

rule_files:
  - /etc/prometheus/alert_rules.yaml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets:
        - 192.168.10.5:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - prometheus:9090
        - node-exporter:9100
        - cadvisor:8080